/// Flutter icons StoryEditIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  StoryEditIcons
///      fonts:
///       - asset: fonts/StoryEditIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class StoryEditIcons {
  StoryEditIcons._();

  static const _kFontFam = 'StoryEditIcons';
  static const String? _kFontPkg = null;

  static const IconData video_frame_2_outline = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sticker_smile_square_outline = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_bin_minimalistic_2_outline = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pen_2_outline = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_outline = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_minimalistic_outline = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle_outline = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up_outline = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_right_outline = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_left_outline = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_horizontal_center_outline = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pen_new_square_outline = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picker_empty = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData outline_photo_filter = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_shine_linear = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ink_marker = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData background_color = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData draw_outline = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gradient_outline = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData draft = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData palette_outline = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xf00c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_left = IconData(0xf036, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_center = IconData(0xf037, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_right = IconData(0xf038, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData long_arrow_alt_up = IconData(0xf30c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bowling_ball = IconData(0xf436, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData palette = IconData(0xf53f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
